version: "2"

services:
  namenode:
    image: sangwonl/hadoop-namenode:latest
    container_name: namenode
    hostname: nginx
    networks:
      - hadoop
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: sangwonl/hadoop-resourcemanager:latest
    container_name: resourcemanager
    hostname: resourcemanager
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode1
      - datanode2
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: sangwonl/hadoop-historyserver:latest
    container_name: historyserver
    hostname: historyserver
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: sangwonl/hadoop-nodemanager:latest
    container_name: nodemanager
    hostname: nodemanager
    networks:
      - hadoop
    depends_on:
      - namenode
      - resourcemanager
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: sangwonl/hadoop-datanode:latest
    container_name: datanode1
    hostname: datanode1
    networks:
      - hadoop
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: sangwonl/hadoop-datanode:latest
    container_name: datanode2
    hostname: datanode2
    networks:
      - hadoop
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode3:
    image: sangwonl/hadoop-datanode:latest
    container_name: datanode3
    hostname: datanode3
    networks:
      - hadoop
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:

networks:
  hadoop:
    driver: bridge
