version: "2"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    hostname: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    links:
      - namenode
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    build: ./historyserver
    container_name: historyserver
    hostname: historyserver
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode1
      - datanode2      
    links:
      - namenode
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

  nodemanager:
    build: ./nodemanager
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - namenode
      - resourcemanager
    links:
      - namenode
      - resourcemanager
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env

  datanode1:
    build: ./datanode
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    links:
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    build: ./datanode
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode
    links:
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    build: ./datanode
    container_name: datanode3
    hostname: datanode3
    depends_on:
      - namenode
    links:
      - namenode
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
