version: '2.0'

services:
  nginx:
    image: sangwonl/hadoop-nginx:latest
    container_name: nginx
    hostname: nginx
    networks:
      - hadoop
    ports:
      - "8088:8088"
      - "8042:8042"

  namenode:
    image: sangwonl/hadoop-namenode:latest
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: sangwonl/hadoop-resourcemanager:latest
    container_name: resourcemanager
    hostname: resourcemanager
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  historyserver:
    image: sangwonl/hadoop-historyserver:latest
    container_name: historyserver
    hostname: historyserver
    networks:
      - hadoop
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: sangwonl/hadoop-nodemanager:latest
    container_name: nodemanager
    hostname: nodemanager
    networks:
      - hadoop
    env_file:
      - ./hadoop.env

  datanode1:
    image: sangwonl/hadoop-datanode:latest
    container_name: datanode1
    hostname: datanode1
    networks:
      - hadoop
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: sangwonl/hadoop-datanode:latest
    container_name: datanode2
    hostname: datanode2
    networks:
      - hadoop
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

networks:
  hadoop:
    driver: bridge